server:
  port: 8080

config:
  password:${PASSWORD:}

version:
  app:
    release: 1
    name :
      Spring Boot Concepts

spring:
  datasource:
    username: sa
    password: ${PASSWORD:}
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  # http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
  jpa:
    database-platform=org: hibernate.dialect.H2Dialect

#open API Swagger - http://localhost:8080/doc/swagger-ui.html
springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /json

#actuator - http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"