server:
  port: 8080
  servlet:
    context-path: /api

config:
  password:${PASSWORD:}

cloud:
  release: 13
  name: Load Properties From Yaml
  enable: true

# custom label
version:
  app:
    release: 1
    name : 'Spring Boot Concepts'

spring:
  # start logo
  banner:
    location: /banner/logo.txt
  # database configuration
  datasource:
    username: sa
    password: ${PASSWORD:}
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  # http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
  jpa:
    database-platform=org: hibernate.dialect.H2Dialect

#open API Swagger - http://localhost:8080/doc/swagger-ui.html
springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /json


#actuator - http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"