
SERVICE_PATH = "/URL/"
TAG_SERVICE = "URL_SERVICES"
GET_LIST = "OBTAINS REGISTER LIST"
GET_BY_ID = "OBTAINS THE REGISTER USING THE ID FOR THE QUERY"
POST_BY_INFO = "SAVE THE REGISTER"
PUT_BY_INFO = "UPDATE THE REGISTER"
DELETE_BY_ID = "DELETE THE REGISTER USING THE ID FOR THE QUERY"