version: '3'
services:
  app1:
    image: jorgecardona/springboot_concepts:1.0.0
    ports:
    - "5001-5003:8080"
    deploy:
        replicas: 3
    networks:
        - "chat_net"
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    networks:
        - "chat_net"
    depends_on:
      - app1
networks: 
    chat_net:
