version: '3'
services:
  springboot_concepts:
    image: jorgecardona/springboot_concepts:1.0.0
    ports:
    - "5001-5003:8080"
    deploy:
        replicas: 3
    networks:
        - "jorgecardona_net"
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    networks:
        - "jorgecardona_net"
    depends_on:
      - springboot_concepts
networks: 
    jorgecardona_net:
