version: '3'
services:
  springboot_concepts:
    image: jorgecardona/springboot_concepts:1.0.1
    ports:
    - "5001-5005:8080"
    deploy:
        replicas: 5
    restart: always
    networks:
        - "jorgecardona_net"
  nginx:
    build: ./nginx
    container_name: nginx_load_balancer 
    ports:
    - "8080:80"
    restart: always
    networks:
        - "jorgecardona_net"
    depends_on:
      - springboot_concepts
networks: 
    jorgecardona_net: